# Generated by Django 6.0.2 on 2026-02-21 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_price', models.FloatField(default=500)),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('video_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('message', 'Message')], max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='upcoming', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
