# Generated by Django 6.0.2 on 2026-02-21 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone  # <-- add this

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now  # <-- correct default
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='patient_appointments',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]