# Generated by Django 6.0.2 on 2026-02-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='site_name',
            field=models.CharField(default='Eye Cognizance', max_length=100),
        ),
    ]
