# Generated by Django 6.0.2 on 2026-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_systemsettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='locked_slots',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
