# Generated by Django 6.0.2 on 2026-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_mobile',
            field=models.CharField(blank=True, help_text='Mobile number of the patient entered during booking', max_length=20, null=True),
        ),
    ]
