# Generated by Django 6.0.2 on 2026-03-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_dob',
        ),
    ]
