# Generated by Django 6.0.2 on 2026-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_remove_appointment_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_dob',
            field=models.DateField(blank=True, help_text='Date of birth of the patient', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
