# Generated by Django 6.0.2 on 2026-03-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_patient_owner_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='custom_time_ranges',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
