# Generated by Django 6.0.3 on 2026-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_systemsettings_custom_time_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='emergency_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
