# Generated by Django 6.0.3 on 2026-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_appointment_emergency_rescheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_document',
            field=models.FileField(blank=True, null=True, upload_to='cancellation_docs/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
