# Generated by Django 5.1.4 on 2026-04-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='doctor_notes',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='treatment_type',
            new_name='opticals_advised',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='opticals',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='prescription',
            name='le_add',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Left Eye ADD'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='le_axis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Left Eye AXIS'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='le_cyl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Left Eye CYL'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='le_sph',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Left Eye SPH'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='le_va',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Left Eye VA'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='re_add',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Right Eye ADD'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='re_axis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Right Eye AXIS'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='re_cyl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Right Eye CYL'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='re_sph',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Right Eye SPH'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='re_va',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Right Eye VA'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_advised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='List of medicines and dosages', null=True),
        ),
    ]
